version: '3.9'

services:
  templates_db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: templates
      POSTGRES_PASSWORD: postgres

  templates_memory:
    image: redis:6.2.3
    ports:
      - "6379:6379"