"""empty message

Revision ID: e22ba4b6dd5b
Revises: 
Create Date: 2022-05-27 08:44:32.040165

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e22ba4b6dd5b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "templates",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("tokens", sa.JSON(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_templates_external_id"), "templates", ["external_id"], unique=False
    )
    op.create_index(op.f("ix_templates_id"), "templates", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_templates_id"), table_name="templates")
    op.drop_index(op.f("ix_templates_external_id"), table_name="templates")
    op.drop_table("templates")
    # ### end Alembic commands ###
